#include "openatc/ui.hpp"
#include "openatc/branding.hpp"
#include "openatc_fonts.hpp"
#include <array>
#include <chrono>
#include <cctype>
#include <cstdio>
#include <vector>

namespace openatc {
namespace {
const ImVec4 accent{0.31f,0.79f,0.94f,1},muted{0.61f,0.67f,0.74f,1},amber{1,0.73f,0.36f,1};
const char* pages[]={"ATC","Flight Plan","Taxi","Arrival","Airports","Settings"};
void drawBrandLogo(ImDrawList* drawing,ImVec2 origin,float size,ImU32 color){
    const float scale=size/64.0f;
    auto project=[&](float horizontal,float vertical){return ImVec2{origin.x+horizontal*scale,origin.y+vertical*scale};};
    auto quadrilateral=[&](std::array<ImVec2,4> coordinates){for(auto& coordinate:coordinates)coordinate=project(coordinate.x,coordinate.y);drawing->AddConvexPolyFilled(coordinates.data(),static_cast<int>(coordinates.size()),color);};
    for(float radius:{11.0f,18.0f}){
        constexpr int segmentCount=20;
        ImVec2 previousPoint{};
        for(int segment=0;segment<=segmentCount;++segment){
            const float angle=(-145.0f+110.0f*segment/segmentCount)*3.141592653589793f/180.0f;
            const ImVec2 nextPoint=project(32+radius*std::cos(angle),20+radius*std::sin(angle));
            if(segment>0)drawing->AddLine(previousPoint,nextPoint,color,2.5f*scale);
            previousPoint=nextPoint;
        }
    }
    drawing->AddLine(project(32,16),project(32,23),color,2.5f*scale);
    quadrilateral({{{14,23},{50,23},{48,27},{16,27}}});
    quadrilateral({{{16,27},{20,27},{24,39},{20,39}}});
    quadrilateral({{{44,27},{48,27},{44,39},{40,39}}});
    quadrilateral({{{30,27},{34,27},{34,39},{30,39}}});
    quadrilateral({{{20,36},{44,36},{44,40},{20,40}}});
    quadrilateral({{{28,40},{36,40},{39,56},{25,56}}});
    drawing->AddRectFilled(project(20,56),project(44,60),color,scale);
}
}
double uiTimeSeconds(){return std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count();}
bool editText(const char* label,std::string& value,size_t capacity,ImGuiInputTextFlags flags){std::vector<char> buffer(std::max(capacity,value.size()+1),0);std::copy(value.begin(),value.end(),buffer.begin());bool changed=ImGui::InputText(label,buffer.data(),buffer.size(),flags);value=buffer.data();return changed;}
bool editParagraph(const char* label,std::string& value,float height,size_t capacity){std::vector<char> buffer(std::max(capacity,value.size()+1),0);std::copy(value.begin(),value.end(),buffer.begin());bool changed=ImGui::InputTextMultiline(label,buffer.data(),buffer.size(),{-1,height});value=buffer.data();return changed;}
void sectionTitle(const char* title){ImGui::Spacing();ImGui::TextColored(accent,"%s",title);ImGui::Separator();ImGui::Spacing();}
void Interface::configureFonts(){auto& input=ImGui::GetIO();ImFontConfig configuration;configuration.FontDataOwnedByAtlas=false;configuration.OversampleH=2;configuration.OversampleV=2;configuration.PixelSnapH=false;auto* body=input.Fonts->AddFontFromMemoryTTF(const_cast<unsigned char*>(bodyFontData),sizeof(bodyFontData),36,&configuration);body->Scale=0.5f;auto* heading=input.Fonts->AddFontFromMemoryTTF(const_cast<unsigned char*>(headingFontData),sizeof(headingFontData),52,&configuration);heading->Scale=0.5f;input.FontDefault=body;}
void Interface::configureStyle(){ImGui::StyleColorsDark();auto& style=ImGui::GetStyle();style.WindowPadding={16,16};style.FramePadding={12,9};style.ItemSpacing={12,10};style.WindowRounding=0;style.ChildRounding=8;style.FrameRounding=5;style.GrabRounding=5;style.PopupRounding=8;style.ScrollbarSize=11;style.WindowBorderSize=0;style.ChildBorderSize=1;style.AntiAliasedLines=true;style.AntiAliasedFill=true;style.SelectableTextAlign={0,0.5f};style.ButtonTextAlign={0.5f,0.5f};auto* colors=style.Colors;colors[ImGuiCol_WindowBg]={0.105f,0.125f,0.15f,0.97f};colors[ImGuiCol_ChildBg]={0.13f,0.155f,0.185f,1};colors[ImGuiCol_Border]={0.22f,0.27f,0.31f,1};colors[ImGuiCol_FrameBg]={0.09f,0.11f,0.14f,1};colors[ImGuiCol_Button]={0.20f,0.25f,0.30f,1};colors[ImGuiCol_ButtonHovered]={0.20f,0.38f,0.46f,1};colors[ImGuiCol_ButtonActive]={0.15f,0.45f,0.56f,1};colors[ImGuiCol_Header]={0.17f,0.33f,0.41f,1};colors[ImGuiCol_HeaderHovered]={0.22f,0.39f,0.47f,1};colors[ImGuiCol_CheckMark]=accent;colors[ImGuiCol_SliderGrab]=accent;colors[ImGuiCol_Text]={0.93f,0.95f,0.97f,1};colors[ImGuiCol_TextDisabled]=muted;}
void drawSymbol(ImDrawList* draw,int symbol,ImVec2 center,ImU32 color,float radius){auto point=[&](float horizontal,float vertical){return ImVec2{center.x+horizontal*radius,center.y+vertical*radius};};auto line=[&](float x1,float y1,float x2,float y2){draw->AddLine(point(x1,y1),point(x2,y2),color,1.7f);};switch(symbol){case 0:draw->AddRect(point(-0.7f,-0.65f),point(0.7f,0.5f),color,3,0,1.7f);line(-0.4f,0.5f,-0.65f,0.85f);line(-0.65f,0.85f,0.05f,0.5f);line(-0.4f,-0.2f,0.4f,-0.2f);line(-0.4f,0.1f,0.1f,0.1f);break;case 1:draw->AddRect(point(-0.65f,-0.85f),point(0.65f,0.85f),color,2,0,1.7f);line(-0.3f,-0.4f,0.3f,-0.4f);line(-0.3f,0,0.3f,0);line(-0.3f,0.4f,0.1f,0.4f);break;case 2:line(-0.8f,0.65f,-0.2f,0.65f);line(-0.2f,0.65f,-0.2f,-0.6f);line(-0.2f,-0.6f,0.7f,-0.6f);draw->AddCircle(point(-0.8f,0.65f),3,color,12,1.5f);draw->AddCircleFilled(point(0.7f,-0.6f),3,color);break;case 3:line(0,-0.9f,0,0.85f);line(-0.85f,0.2f,0,-0.3f);line(0,-0.3f,0.85f,0.2f);line(-0.4f,0.8f,0,0.5f);line(0,0.5f,0.4f,0.8f);break;case 4:line(-0.7f,0.8f,0.7f,0.8f);line(-0.35f,0.8f,-0.35f,-0.2f);line(0.35f,0.8f,0.35f,-0.2f);draw->AddRect(point(-0.65f,-0.7f),point(0.65f,-0.15f),color,1,0,1.7f);line(0,-0.7f,0,-1);break;case 5:for(int index=0;index<3;++index){float vertical=(index-1)*0.65f;line(-0.85f,vertical,0.85f,vertical);draw->AddCircleFilled(point(index==1?0.35f:-0.25f,vertical),3.5f,color);}break;}}
void Interface::metric(const char* title,const std::string& value,float width){ImGui::BeginChild(title,{width,46+44*settings_.uiScale},ImGuiChildFlags_Borders,ImGuiWindowFlags_NoScrollbar);ImGui::TextColored(muted,"%s",title);if(ImGui::GetIO().Fonts->Fonts.Size>1)ImGui::PushFont(ImGui::GetIO().Fonts->Fonts[1]);ImGui::TextUnformatted(value.c_str());if(ImGui::GetIO().Fonts->Fonts.Size>1)ImGui::PopFont();ImGui::EndChild();}
void Interface::send(Request request){engine_.post("/request",request);}
void Interface::saveSettings(){if(!settingsLoaded_||!engine_.connected()){settingsNotice_="Connect to the engine before saving settings.";return;}engine_.post("/settings",settings_);lastSettingsJson_=Json(settings_).dump();settingsNotice_="Saving settings...";}
void Interface::loadAirport(const std::string& icao){airportCode_=icao;loadingAirport_=true;airportNotice_="Loading airport data...";engine_.post("/airport/load",{{"icao",icao}});}
void Interface::pollReplies(){
    if(auto reply=engine_.takeReply("/simbrief")){importing_=false;if(reply->success){try{draft_=reply->data.get<FlightPlan>();planLoaded_=true;planNotice_="Downloaded latest OFP. Review the dispatch fields, then use this flight.";}catch(const std::exception& error){planNotice_=error.what();}}else planNotice_=reply->error;}
    if(auto reply=engine_.takeReply("/plan")){planNotice_=reply->success?"Flight plan accepted by OpenATC AI.":reply->error;}
    if(auto reply=engine_.takeReply("/airport/load")){loadingAirport_=false;if(reply->success){airport_=reply->data.get<Airport>();zoom_=1;pan_={};airportNotice_="Loaded "+airport_.icao+" from installed scenery.";}else airportNotice_=reply->error;}
    if(auto reply=engine_.takeReply("/settings")){settingsNotice_=reply->success?"Settings saved":reply->error;}
    if(auto reply=engine_.takeReply("/session/reset")){if(reply->success){draft_=reply->data.at("plan").get<FlightPlan>();planLoaded_=true;lastSpeechSequence_=0;lastTranscriptSequence_=0;speechQueue_.clear();planNotice_="Flight reset.";}else settingsNotice_=reply->error;}
    if(auto reply=engine_.takeReply("/request")){if(!reply->success)notice_=reply->error;else notice_.clear();}
}
void Interface::updateSpeech(const State& state){speech_.configure(settings_.inputDevice,settings_.outputDevice,settings_.inputGain,settings_.masterVolume);speech_.poll();auto transcription=speech_.takeTranscript();if(!transcription.empty())message_=transcription;
    if(state.transcript.empty())lastSpeechSequence_=0;
    for(const auto& entry:state.transcript)if(entry.sequence>lastSpeechSequence_){bool controller=entry.speaker=="ATC";bool pilot=!controller&&entry.speaker!="COPILOT"&&entry.speaker!="CABIN"&&entry.speaker!="GROUND";if((controller&&settings_.controllerSpeech)||(entry.speaker=="COPILOT"&&settings_.copilotSpeech&&settings_.copilotReplies)||(pilot&&settings_.pilotSpeech)||entry.speaker=="CABIN"||entry.speaker=="GROUND")speechQueue_.push_back(entry);lastSpeechSequence_=entry.sequence;}
    while(speechQueue_.size()>20)speechQueue_.pop_front();if(!speechQueue_.empty()&&!speech_.busy()&&!speech_.recording()&&!speech_.monitoring()){auto entry=speechQueue_.front();speechQueue_.pop_front();speakEntry(entry);}
}
void Interface::speakEntry(const Transmission& entry){int role=entry.speaker=="GROUND"?4:(entry.speaker=="CABIN"?3:(entry.speaker=="COPILOT"?1:(entry.speaker=="ATC"?0:2)));float volume=role==4?settings_.groundVolume:(role==3?settings_.attendantVolume:(role==1?settings_.copilotVolume:(role==2?settings_.pilotVolume:settings_.controllerVolume)));speech_.speak(entry.text,engine_.endpoint(),role,volume,entry.voice,entry.speed,entry.urgent,entry.delivery);}
void Interface::tick(){pollReplies();auto state=engine_.state();if(engine_.connected()&&!settingsLoaded_){settings_=engine_.settings();lastSettingsJson_=Json(settings_).dump();settingsLoaded_=true;lastSpeechSequence_=state.transcript.empty()?0:state.transcript.back().sequence;}if(settingsLoaded_&&settings_.simulatorRoot.empty())settings_.simulatorRoot=engine_.settings().simulatorRoot;if(engine_.connected()&&!planLoaded_){draft_=state.plan;planLoaded_=true;}
    updateSpeech(state);}
void Interface::draw(ImVec2 position,ImVec2 size){tick();auto state=engine_.state();ImGui::GetIO().FontGlobalScale=settings_.uiScale;auto& input=ImGui::GetIO();bool inside=input.MousePos.x>=position.x&&input.MousePos.y>=position.y&&input.MousePos.x<position.x+size.x&&input.MousePos.y<position.y+size.y;if(inside||input.WantTextInput||ImGui::IsAnyItemActive()||ImGui::IsPopupOpen(nullptr,ImGuiPopupFlags_AnyPopupId))lastInteraction_=uiTimeSeconds();bool faded=page_==0&&!settings_.pinOpen&&uiTimeSeconds()-lastInteraction_>settings_.fadeDelay;
    ImGui::SetNextWindowPos(position);ImGui::SetNextWindowSize(size);ImGui::SetNextWindowBgAlpha(faded?settings_.fadedOpacity:0.98f);ImGui::Begin(productName,nullptr,ImGuiWindowFlags_NoDecoration|ImGuiWindowFlags_NoMove|ImGuiWindowFlags_NoSavedSettings);
    if(faded){ImGui::TextColored(accent,"%s / %s",productName,state.plan.callsign.c_str());int start=std::max(0,static_cast<int>(state.transcript.size())-5);for(int index=start;index<static_cast<int>(state.transcript.size());++index){const auto& entry=state.transcript[index];ImGui::TextColored(muted,"%s",entry.speaker.c_str());ImGui::TextWrapped("%s",entry.text.c_str());}ImGui::End();return;}
    const float logoSize=44*settings_.uiScale,brandGap=8*settings_.uiScale,wordGap=5*settings_.uiScale,brandHeight=56*settings_.uiScale;
    const ImVec2 nameSize=ImGui::CalcTextSize("OpenATC"),suffixSize=ImGui::CalcTextSize("AI");
    const float brandWidth=logoSize+brandGap+nameSize.x+wordGap+suffixSize.x;
    const float sidebar=std::max(220*settings_.uiScale,brandWidth+ImGui::GetStyle().WindowPadding.x*2+4);
    ImGui::BeginChild("Navigation",{sidebar,0},ImGuiChildFlags_Borders);
    const ImVec2 brandOrigin=ImGui::GetCursorScreenPos();
    auto* brandDrawing=ImGui::GetWindowDrawList();
    drawBrandLogo(brandDrawing,{brandOrigin.x,brandOrigin.y+(brandHeight-logoSize)/2},logoSize,IM_COL32(79,202,240,255));
    const ImVec2 namePosition{brandOrigin.x+logoSize+brandGap,brandOrigin.y+(brandHeight-nameSize.y)/2};
    brandDrawing->AddText(namePosition,IM_COL32(237,243,248,255),"OpenATC");
    brandDrawing->AddText({namePosition.x+nameSize.x+wordGap,namePosition.y},IM_COL32(79,202,240,255),"AI");
    ImGui::Dummy({brandWidth,brandHeight});ImGui::Dummy({0,12*settings_.uiScale});
    for(int index=0;index<6;++index){ImGui::PushID(index);ImVec2 start=ImGui::GetCursorScreenPos(),buttonSize{ImGui::GetContentRegionAvail().x,46*settings_.uiScale};if(ImGui::InvisibleButton("Navigation item",buttonSize))page_=index;auto* draw=ImGui::GetWindowDrawList();if(page_==index||ImGui::IsItemHovered())draw->AddRectFilled(start,{start.x+buttonSize.x,start.y+buttonSize.y},page_==index?IM_COL32(42,81,102,255):IM_COL32(49,60,71,255),5);if(page_==index)draw->AddRectFilled({start.x,start.y+9},{start.x+3,start.y+buttonSize.y-9},IM_COL32(79,202,240,255),2);auto textSize=ImGui::CalcTextSize(pages[index]);drawSymbol(draw,index,{start.x+23,start.y+buttonSize.y/2},page_==index?IM_COL32(91,212,248,255):IM_COL32(157,173,190,255));draw->AddText({start.x+45,start.y+(buttonSize.y-textSize.y)/2},IM_COL32(234,240,247,255),pages[index]);ImGui::PopID();}
    ImGui::Dummy({0,18});ImGui::Separator();ImGui::TextColored(muted,"%s  %s",productName,productVersion);ImGui::TextWrapped("%s",engine_.status().c_str());ImGui::EndChild();ImGui::SameLine();
    ImGui::BeginChild("Content",{0,0},ImGuiChildFlags_None);ImGui::TextColored(muted,"%s   /   %s  >  %s",state.plan.callsign.c_str(),state.plan.departure.c_str(),state.plan.destination.c_str());ImGui::SameLine();ImGui::TextColored(state.demo?amber:accent,"%s",state.demo?"DEMO":"SIMULATOR");if(ImGui::GetIO().Fonts->Fonts.Size>1)ImGui::PushFont(ImGui::GetIO().Fonts->Fonts[1]);ImGui::TextUnformatted(pages[page_]);if(ImGui::GetIO().Fonts->Fonts.Size>1)ImGui::PopFont();ImGui::Spacing();
    switch(page_){case 0:atcPage(state);break;case 1:planPage(state);break;case 2:taxiPage(state);break;case 3:arrivalPage(state);break;case 4:airportsPage(state);break;case 5:settingsPage(state);break;}
    ImGui::EndChild();ImGui::End();
    auto serialized=Json(settings_).dump();if(settingsLoaded_&&engine_.connected()&&serialized!=lastSettingsJson_){if(settingsChangedAt_==0)settingsChangedAt_=uiTimeSeconds();if(uiTimeSeconds()-settingsChangedAt_>1&&!ImGui::IsAnyItemActive()){saveSettings();settingsChangedAt_=0;}}else settingsChangedAt_=0;
}
void Interface::drawRequestDialog(const State& state){UnitSystem units=resolveUnits(settings_.units,state.plan.departure);bool metric=units==UnitSystem::Metric;if(ImGui::BeginPopupModal("ATC request",nullptr,ImGuiWindowFlags_AlwaysAutoResize)){ImGui::TextUnformatted(modalTitle_.c_str());ImGui::Spacing();if(modalIntent_=="direct"){ImGui::SetNextItemWidth(320);editText("Waypoint",requestedWaypoint_,32,ImGuiInputTextFlags_CharsUppercase);}else{ImGui::SetNextItemWidth(230);int shown=metric?static_cast<int>(std::lround(feetToMeters(requestedAltitude_)/10)*10):requestedAltitude_;int before=shown;ImGui::InputInt(metric?"Altitude (m)":"Altitude (ft)",&shown,metric?10:1000);if(shown!=before)requestedAltitude_=metric?metersToFeet(shown):shown;ImGui::TextDisabled("Current altitude: %s",altitudeText(state.telemetry.altitudeFeet,units,false).c_str());}bool available=requestAvailable(state,modalIntent_);if(!available)ImGui::TextColored(amber,"Flight stage changed. Request no longer available.");ImGui::BeginDisabled(!available||!engine_.connected());if(ImGui::Button("Send request",{150,0})){Request request;request.intent=modalIntent_;request.altitudeFeet=requestedAltitude_;request.waypoint=requestedWaypoint_;request.text=modalIntent_=="direct"?"Request direct to "+requestedWaypoint_:"Request "+modalIntent_+" "+altitudeText(requestedAltitude_,units,true);send(request);ImGui::CloseCurrentPopup();}ImGui::EndDisabled();ImGui::SameLine();if(ImGui::Button("Cancel",{100,0})||ImGui::IsKeyPressed(ImGuiKey_Escape))ImGui::CloseCurrentPopup();ImGui::EndPopup();}}
void Interface::atcPage(const State& state){ImGui::Checkbox("Keep open",&settings_.pinOpen);ImGui::SameLine();ImGui::TextColored(accent,"%s",phaseName(state.phase).c_str());if(state.telemetry.com1Khz>0){ImGui::SameLine();ImGui::TextDisabled("COM1 %.3f",state.telemetry.com1Khz/1000.0);}
    if(state.clearance){const auto& clearance=*state.clearance;ImGui::BeginChild("Clearance",{0,44+40*settings_.uiScale},ImGuiChildFlags_Borders,ImGuiWindowFlags_NoScrollbar);ImGui::TextColored(accent,"CLEARANCE #%u   %s",clearance.sequence,clearance.acknowledged?"READ BACK":"READBACK REQUIRED");ImGui::TextWrapped("%s  /  %s  /  Squawk %s  /  Runway %s",altitudeText(clearance.altitudeFeet,resolveUnits(settings_.units,state.plan.departure),false).c_str(),clearance.route.c_str(),clearance.squawk.c_str(),clearance.runway.c_str());ImGui::EndChild();}
    float transcriptHeight=std::max(130.0f,ImGui::GetContentRegionAvail().y-265);ImGui::BeginChild("Transcript",{0,transcriptHeight},ImGuiChildFlags_Borders);if(state.transcript.empty()){ImGui::TextColored(accent,"Ready when you are");ImGui::TextWrapped("Set up your flight plan, then request clearance. Available requests follow your flight stage.");}
    for(const auto& entry:state.transcript){ImGui::PushID(static_cast<int>(entry.sequence));std::string who=entry.speaker+(entry.position.empty()?"":(" · "+entry.position));ImGui::TextColored(entry.speaker=="ATC"?accent:muted,"%s",who.c_str());ImGui::TextWrapped("%s",entry.text.c_str());ImGui::Spacing();ImGui::PopID();}if(!state.transcript.empty()&&state.transcript.back().sequence!=lastTranscriptSequence_){lastTranscriptSequence_=state.transcript.back().sequence;ImGui::SetScrollHereY(1);}ImGui::EndChild();
    ImGui::TextDisabled("CALLS");ImGui::SameLine();const char* calls[3]={"ATC","CABIN","GND"};for(int index=0;index<3;++index){if(index)ImGui::SameLine();if(ImGui::RadioButton(calls[index],commRole_==index))commRole_=index;}
    ImGui::SetNextItemWidth(std::max(120.0f,ImGui::GetContentRegionAvail().x-130));bool submit=editText("##message",message_,4096,ImGuiInputTextFlags_EnterReturnsTrue);ImGui::SameLine();ImGui::BeginDisabled(!engine_.connected());submit=ImGui::Button("Transmit",{118,0})||submit;if(submit&&engine_.connected()&&!message_.empty()){auto request=interpretText(message_);request.role=commRole_==2?"ground":(commRole_==1?"cabin":"atc");send(request);message_.clear();}ImGui::EndDisabled();
    ImGui::BeginDisabled(speech_.busy()||speech_.monitoring());if(ImGui::Button(speech_.recording()?"Stop + transcribe":"Record request")){if(speech_.recording())speech_.transcribe(engine_.endpoint());else speech_.startRecording();}ImGui::SameLine();if(ImGui::Button("Replay ATC")){for(auto entry=state.transcript.rbegin();entry!=state.transcript.rend();++entry)if(entry->speaker=="ATC"){speakEntry(*entry);break;}}ImGui::EndDisabled();ImGui::SameLine();ImGui::TextDisabled("%s",speech_.status().c_str());
    if(!notice_.empty())ImGui::TextWrapped("%s",notice_.c_str());
    ImGui::SetNextItemWidth(220);editText("Filter requests",search_,128);ImGui::BeginChild("Requests",{0,0});int columns=std::max(1,static_cast<int>(ImGui::GetContentRegionAvail().x/(245*settings_.uiScale)));if(ImGui::BeginTable("RequestGrid",columns,ImGuiTableFlags_SizingStretchSame)){for(const auto& definition:requestDefinitions()){if(!requestAvailable(state,definition.intent))continue;std::string title=definition.title,filter=search_;for(char& value:title)value=static_cast<char>(std::tolower(static_cast<unsigned char>(value)));for(char& value:filter)value=static_cast<char>(std::tolower(static_cast<unsigned char>(value)));if(!filter.empty()&&title.find(filter)==std::string::npos)continue;ImGui::TableNextColumn();ImGui::BeginDisabled(!engine_.connected());if(ImGui::Button(definition.title,{-1,38*settings_.uiScale})){if(definition.parameter){modalIntent_=definition.intent;modalTitle_=definition.title;requestedAltitude_=modalIntent_=="descent"?std::max(1000,static_cast<int>(state.telemetry.altitudeFeet)-4000):state.plan.cruiseFeet;}else{Request request;request.intent=definition.intent;request.text=definition.title;if(request.intent=="readback"&&state.clearance){request.clearanceSequence=state.clearance->sequence;request.altitudeFeet=state.clearance->altitudeFeet;request.waypoint=state.clearance->route;}send(request);}}ImGui::EndDisabled();}ImGui::EndTable();}ImGui::EndChild();
    if(!modalIntent_.empty()&&!ImGui::IsPopupOpen("ATC request")){ImGui::OpenPopup("ATC request");}drawRequestDialog(state);if(!ImGui::IsPopupOpen("ATC request"))modalIntent_.clear();
}
}
