#include "openatc/ui.hpp"
#include <map>
#include <array>
#include <ctime>
#include <cstdio>
namespace openatc {
namespace {
void aircraftSymbol(ImDrawList* draw,ImVec2 center,double heading,ImU32 color){double angle=heading*3.141592653589793/180;auto point=[&](float east,float north){return ImVec2{center.x+static_cast<float>(east*std::cos(angle)+north*std::sin(angle)),center.y+static_cast<float>(east*std::sin(angle)-north*std::cos(angle))};};draw->AddTriangleFilled(point(0,13),point(-8,-9),point(0,-5),color);draw->AddTriangleFilled(point(0,13),point(0,-5),point(8,-9),color);draw->AddCircle(center,19,IM_COL32(220,241,252,70),32,1);}
double numeric(const Json& object,const char* key,double fallback=0){if(!object.is_object()||!object.contains(key)||object[key].is_null())return fallback;if(object[key].is_number())return object[key].get<double>();if(object[key].is_string()){try{return std::stod(object[key].get<std::string>());}catch(...){return fallback;}}return fallback;}
std::string textValue(const Json& object,const char* key){if(!object.is_object()||!object.contains(key)||!object[key].is_string())return {};return object[key].get<std::string>();}
}
void Interface::airportCanvas(const State& state,float height){ImVec2 origin=ImGui::GetCursorScreenPos(),size{ImGui::GetContentRegionAvail().x,height>0?height:std::max(180.0f,ImGui::GetContentRegionAvail().y-42)};ImGui::InvisibleButton("AirportCanvas",size,ImGuiButtonFlags_MouseButtonLeft|ImGuiButtonFlags_MouseButtonRight);auto& input=ImGui::GetIO();bool hovered=ImGui::IsItemHovered();if(hovered){zoom_=std::clamp(zoom_*std::pow(1.12f,input.MouseWheel),0.2f,18.0f);if(page_==5&&orbitView_&&ImGui::IsMouseDragging(ImGuiMouseButton_Left)){yaw_+=input.MouseDelta.x*0.008f;pitch_=std::clamp(pitch_+input.MouseDelta.y*0.008f,0.2f,1.5f);}else if(ImGui::IsMouseDragging(ImGuiMouseButton_Left)||ImGui::IsMouseDragging(ImGuiMouseButton_Right)){pan_.x+=input.MouseDelta.x;pan_.y+=input.MouseDelta.y;}}
    auto* draw=ImGui::GetWindowDrawList();draw->PushClipRect(origin,{origin.x+size.x,origin.y+size.y},true);draw->AddRectFilled(origin,{origin.x+size.x,origin.y+size.y},IM_COL32(18,28,36,255),7);
    double minimumEast=1e100,maximumEast=-1e100,minimumNorth=1e100,maximumNorth=-1e100;auto include=[&](const Point& point){minimumEast=std::min(minimumEast,point.east);maximumEast=std::max(maximumEast,point.east);minimumNorth=std::min(minimumNorth,point.north);maximumNorth=std::max(maximumNorth,point.north);};for(const auto& runway:airport_.runways){include(runway.first);include(runway.second);}for(const auto& parking:airport_.parking)include(parking.point);for(const auto& node:airport_.nodes)include(node.point);if(minimumEast>maximumEast){minimumEast=minimumNorth=-500;maximumEast=maximumNorth=500;}double centerEast=(minimumEast+maximumEast)/2,centerNorth=(minimumNorth+maximumNorth)/2;float scale=static_cast<float>(std::min((size.x-100)/std::max(1000.0,maximumEast-minimumEast),(size.y-90)/std::max(1000.0,maximumNorth-minimumNorth)))*zoom_;float angle=page_==5&&orbitView_?yaw_:0,tilt=page_==5&&orbitView_?pitch_:1.5707963f;auto project=[&](const Point& point){double east=point.east-centerEast,north=point.north-centerNorth;return ImVec2{origin.x+size.x/2+pan_.x+static_cast<float>(east*std::cos(angle)-north*std::sin(angle))*scale,origin.y+size.y/2+pan_.y-static_cast<float>((east*std::sin(angle)+north*std::cos(angle))*std::sin(tilt)+point.height*std::cos(tilt))*scale};};
    for(int grid=-12;grid<=12;++grid){double offset=grid*500.0;draw->AddLine(project({centerEast+offset,centerNorth-6000}),project({centerEast+offset,centerNorth+6000}),IM_COL32(32,47,58,255));draw->AddLine(project({centerEast-6000,centerNorth+offset}),project({centerEast+6000,centerNorth+offset}),IM_COL32(32,47,58,255));}
    if(showRunways_)for(const auto& runway:airport_.runways){double east=runway.second.east-runway.first.east,north=runway.second.north-runway.first.north,length=std::hypot(east,north);if(length<1)continue;double normalEast=-north/length*runway.width/2,normalNorth=east/length*runway.width/2;ImVec2 corners[]={project({runway.first.east+normalEast,runway.first.north+normalNorth}),project({runway.second.east+normalEast,runway.second.north+normalNorth}),project({runway.second.east-normalEast,runway.second.north-normalNorth}),project({runway.first.east-normalEast,runway.first.north-normalNorth})};draw->AddConvexPolyFilled(corners,4,IM_COL32(96,111,123,255));draw->AddLine(project(runway.first),project(runway.second),IM_COL32(218,226,234,230),1);if(settings_.showLabels){draw->AddText(project(runway.first),IM_COL32(255,210,133,255),runway.firstName.c_str());draw->AddText(project(runway.second),IM_COL32(255,210,133,255),runway.secondName.c_str());}}
    std::map<long,Point> nodes;for(const auto& node:airport_.nodes)nodes[node.id]=node.point;
    if(settings_.showTaxiways)for(const auto& edge:airport_.edges){if(!nodes.count(edge.first)||!nodes.count(edge.second))continue;auto first=project(nodes.at(edge.first)),second=project(nodes.at(edge.second));draw->AddLine(first,second,edge.runway?IM_COL32(176,99,94,210):IM_COL32(75,112,126,255),std::max(2.0f,18*scale));if(settings_.showLabels&&zoom_>0.65f&&!edge.name.empty())draw->AddText({(first.x+second.x)/2,(first.y+second.y)/2},IM_COL32(153,188,202,255),edge.name.c_str());}
    if(settings_.showTaxiRoute&&state.taxiClearance.approved&&state.taxiClearance.airport==airport_.icao){const auto& points=state.taxiClearance.points;
        if(state.telemetry.positionValid&&!points.empty()){
            auto current=project(airportPoint(airport_,state.telemetry.latitude,state.telemetry.longitude));auto first=project(points.front());float length=std::hypot(first.x-current.x,first.y-current.y);
            if(length>1 && length<350*scale){for(float offset=0;offset<length;offset+=12){float end=std::min(length,offset+6);draw->AddLine({current.x+(first.x-current.x)*offset/length,current.y+(first.y-current.y)*offset/length},{current.x+(first.x-current.x)*end/length,current.y+(first.y-current.y)*end/length},IM_COL32(255,192,87,255),2);}}
        }
        for(size_t index=1;index<points.size();++index)draw->AddLine(project(points[index-1]),project(points[index]),IM_COL32(64,223,168,255),4);if(!points.empty()){auto endpoint=project(points.back());draw->AddCircle(endpoint,9,IM_COL32(255,192,87,255),24,3);draw->AddText({endpoint.x+13,endpoint.y-12},IM_COL32(255,192,87,255),"STOP");}}
    if(settings_.showParking)for(const auto& parking:airport_.parking){auto position=project(parking.point);ImU32 color=parking.type=="gate"?IM_COL32(115,175,235,255):IM_COL32(170,145,213,255);draw->AddRectFilled({position.x-5,position.y-5},{position.x+5,position.y+5},color,2);if(settings_.showLabels)draw->AddText({position.x+8,position.y-8},IM_COL32(214,226,237,255),parking.name.c_str());if(hovered&&std::hypot(input.MousePos.x-position.x,input.MousePos.y-position.y)<13){ImGui::BeginTooltip();ImGui::Text("%s / %s",parking.name.c_str(),parking.type.c_str());ImGui::Text("Size %s / %s",parking.size.c_str(),parking.equipment.c_str());ImGui::EndTooltip();}}
    if(page_==5&&orbitView_&&showBuildings_&&airport_.icao=="DEMO"){
        struct Face {std::array<Point,4> corners;ImU32 color;double depth;};std::vector<Face> faces;
        auto box=[&](double east,double north,double width,double depth,double height){Point points[]={{east,north,0},{east+width,north,0},{east+width,north+depth,0},{east,north+depth,0},{east,north,height},{east+width,north,height},{east+width,north+depth,height},{east,north+depth,height}};int indices[][4]={{0,1,5,4},{1,2,6,5},{2,3,7,6},{3,0,4,7},{4,5,6,7}};for(int side=0;side<5;++side){Face face;face.color=side==4?IM_COL32(118,152,165,255):IM_COL32(49+side*9,75+side*8,90+side*8,255);face.depth=0;for(int corner=0;corner<4;++corner){face.corners[corner]=points[indices[side][corner]];const auto& point=face.corners[corner];face.depth+=point.east*std::sin(angle)+point.north*std::cos(angle);}faces.push_back(face);}};
        box(-450,480,850,120,65);box(-400,330,70,150,35);box(260,330,70,150,35);box(550,450,60,65,150);std::sort(faces.begin(),faces.end(),[](const Face& first,const Face& second){return first.depth>second.depth;});for(const auto& face:faces){ImVec2 points[4];for(int index=0;index<4;++index)points[index]=project(face.corners[index]);draw->AddConvexPolyFilled(points,4,face.color);}
    }
    if(showNavaids_&&page_==5)for(const auto& navaid:airport_.navaids){auto position=project(airportPoint(airport_,navaid.latitude,navaid.longitude));draw->AddCircle(position,5,IM_COL32(202,160,241,255),6,2);if(settings_.showLabels)draw->AddText({position.x+7,position.y},IM_COL32(202,160,241,255),navaid.identifier.c_str());}
    if(settings_.showOwnship){if(state.telemetry.positionValid){auto point=airportPoint(airport_,state.telemetry.latitude,state.telemetry.longitude);if(std::hypot(point.east,point.north)<100000)aircraftSymbol(draw,project(point),state.telemetry.headingDegrees,IM_COL32(246,251,255,255));else draw->AddText({origin.x+16,origin.y+44},IM_COL32(245,190,100,255),"Aircraft is outside this airport area");}else draw->AddText({origin.x+16,origin.y+44},IM_COL32(160,177,193,255),"Aircraft position unavailable");}
    draw->AddText({origin.x+16,origin.y+14},IM_COL32(163,188,207,255),page_==5&&orbitView_?"3D / drag to orbit / right-drag to pan":"NORTH UP / wheel to zoom / drag to pan");float bar=std::min(size.x*0.25f,500*scale);draw->AddLine({origin.x+20,origin.y+size.y-24},{origin.x+20+bar,origin.y+size.y-24},IM_COL32(198,214,227,255),2);char scaleText[32];std::snprintf(scaleText,sizeof(scaleText),"%.0f m",bar/scale);draw->AddText({origin.x+22,origin.y+size.y-48},IM_COL32(198,214,227,255),scaleText);draw->PopClipRect();ImGui::TextDisabled("%s / %zu parking positions / dashed amber: unverified ramp connector",airport_.icao.c_str(),airport_.parking.size());
}
void Interface::weatherCanvas(const State& state,float height){ImVec2 origin=ImGui::GetCursorScreenPos(),size{ImGui::GetContentRegionAvail().x,height};ImGui::InvisibleButton("WeatherMap",size,ImGuiButtonFlags_MouseButtonLeft);auto& input=ImGui::GetIO();bool hovered=ImGui::IsItemHovered();if(hovered){weatherZoom_=std::clamp(weatherZoom_*std::pow(1.12f,input.MouseWheel),0.3f,18.0f);if(ImGui::IsMouseDragging(ImGuiMouseButton_Left)){weatherPan_.x+=input.MouseDelta.x;weatherPan_.y+=input.MouseDelta.y;}}
    double referenceLongitude=!state.plan.fixes.empty()?state.plan.fixes.front().longitude:state.telemetry.longitude;auto unwrap=[&](double longitude){return referenceLongitude+std::remainder(longitude-referenceLongitude,360.0);};double minimumLatitude=90,maximumLatitude=-90,minimumLongitude=1e100,maximumLongitude=-1e100;auto include=[&](double latitude,double longitude){if(!std::isfinite(latitude)||!std::isfinite(longitude))return;minimumLatitude=std::min(minimumLatitude,latitude);maximumLatitude=std::max(maximumLatitude,latitude);minimumLongitude=std::min(minimumLongitude,unwrap(longitude));maximumLongitude=std::max(maximumLongitude,unwrap(longitude));};for(const auto& fix:state.plan.fixes)include(fix.latitude,fix.longitude);if(state.telemetry.positionValid)include(state.telemetry.latitude,state.telemetry.longitude);for(const auto& report:weatherReports_)if(report.contains("lat")&&report.contains("lon"))include(numeric(report,"lat"),numeric(report,"lon"));if(minimumLatitude>maximumLatitude){minimumLatitude=-42;maximumLatitude=-37;minimumLongitude=144;maximumLongitude=149;}
    double centerLatitude=(minimumLatitude+maximumLatitude)/2,centerLongitude=(minimumLongitude+maximumLongitude)/2;double cosine=std::max(0.05,std::cos(centerLatitude*3.141592653589793/180));double scale=std::min((size.x-120)/std::max(1.0,(maximumLongitude-minimumLongitude)*cosine),(size.y-100)/std::max(1.0,maximumLatitude-minimumLatitude))*weatherZoom_;auto project=[&](double latitude,double longitude){return ImVec2{origin.x+size.x/2+weatherPan_.x+static_cast<float>((unwrap(longitude)-centerLongitude)*cosine*scale),origin.y+size.y/2+weatherPan_.y-static_cast<float>((latitude-centerLatitude)*scale)};};auto* draw=ImGui::GetWindowDrawList();draw->PushClipRect(origin,{origin.x+size.x,origin.y+size.y},true);draw->AddRectFilled(origin,{origin.x+size.x,origin.y+size.y},IM_COL32(17,30,42,255),7);
    double spacing=std::max(0.5,std::ceil((maximumLatitude-minimumLatitude)/8));for(int index=-10;index<=10;++index){double latitude=std::floor(centerLatitude/spacing)*spacing+index*spacing,longitude=std::floor(centerLongitude/spacing)*spacing+index*spacing;auto horizontal=project(latitude,centerLongitude),vertical=project(centerLatitude,longitude);draw->AddLine({origin.x,horizontal.y},{origin.x+size.x,horizontal.y},IM_COL32(34,52,66,255));draw->AddLine({vertical.x,origin.y},{vertical.x,origin.y+size.y},IM_COL32(34,52,66,255));char label[32];std::snprintf(label,sizeof(label),"%.1f",latitude);draw->AddText({origin.x+6,horizontal.y+2},IM_COL32(83,111,134,255),label);}
    if(settings_.weatherRoute&&state.plan.fixes.size()>1){for(size_t index=1;index<state.plan.fixes.size();++index){const auto& first=state.plan.fixes[index-1];const auto& second=state.plan.fixes[index];draw->AddLine(project(first.latitude,first.longitude),project(second.latitude,second.longitude),IM_COL32(82,195,241,255),2.5f);}for(size_t index=0;index<state.plan.fixes.size();++index){const auto& fix=state.plan.fixes[index];auto position=project(fix.latitude,fix.longitude);draw->AddCircleFilled(position,3,IM_COL32(113,207,248,255));if(settings_.weatherLabels&&(index==0||index+1==state.plan.fixes.size()||weatherZoom_>2))draw->AddText({position.x+7,position.y+6},IM_COL32(171,220,245,255),fix.identifier.c_str());}}
    if(page_==6)for(const auto& report:weatherReports_){if(!report.contains("lat")||!report.contains("lon"))continue;auto position=project(numeric(report,"lat"),numeric(report,"lon"));std::string category=textValue(report,"fltCat");ImU32 color=category=="VFR"?IM_COL32(83,212,152,255):category=="MVFR"?IM_COL32(88,167,246,255):category=="IFR"?IM_COL32(243,104,112,255):category=="LIFR"?IM_COL32(203,120,244,255):IM_COL32(165,177,185,255);
        if(settings_.weatherClouds){double coverage=0;if(report.contains("clouds")&&report["clouds"].is_array())for(const auto& layer:report["clouds"]){auto cover=textValue(layer,"cover");coverage=std::max(coverage,cover=="OVC"?1.0:cover=="BKN"?0.75:cover=="SCT"?0.4:cover=="FEW"?0.2:0);}if(coverage>0)draw->AddCircleFilled(position,13+static_cast<float>(coverage)*16,IM_COL32(175,193,217,static_cast<int>(coverage*80)));}
        if(settings_.weatherStations){draw->AddCircleFilled(position,7,color);draw->AddCircle(position,10,color,24,1.4f);}if(settings_.weatherLabels)draw->AddText({position.x+14,position.y-20},color,textValue(report,"icaoId").c_str());
        if(settings_.weatherWind&&numeric(report,"wspd")>0&&report.contains("wdir")&&report["wdir"].is_number()){double angle=numeric(report,"wdir")*3.141592653589793/180;float length=22+std::min(30.0,numeric(report,"wspd"));ImVec2 tip{position.x+static_cast<float>(std::sin(angle))*length,position.y-static_cast<float>(std::cos(angle))*length};draw->AddLine(position,tip,color,2);draw->AddCircleFilled(tip,3,color);}
        if(hovered&&std::hypot(input.MousePos.x-position.x,input.MousePos.y-position.y)<24){ImGui::BeginTooltip();ImGui::Text("%s / %s",textValue(report,"icaoId").c_str(),category.c_str());ImGui::PushTextWrapPos(500);ImGui::TextUnformatted(textValue(report,"rawOb").c_str());ImGui::PopTextWrapPos();double observed=numeric(report,"obsTime");if(observed>0){double age=(std::time(nullptr)-observed)/60;ImGui::Text("Observation age: %.0f minutes",std::max(0.0,age));}ImGui::TextDisabled("Wind shaft points toward the direction wind comes from.");ImGui::EndTooltip();}}
    if(settings_.weatherOwnship&&state.telemetry.positionValid)aircraftSymbol(draw,project(state.telemetry.latitude,state.telemetry.longitude),state.telemetry.headingDegrees,IM_COL32(250,252,255,255));draw->AddText({origin.x+16,origin.y+14},IM_COL32(155,184,205,255),page_==6?"WEATHER / georeferenced station observations":"FLIGHT ROUTE / imported coordinates");if(state.plan.fixes.size()<2)draw->AddText({origin.x+16,origin.y+44},IM_COL32(230,185,108,255),"Import a SimBrief OFP to map the route");draw->PopClipRect();
}
}
