#include "openatc/ui.hpp"
#include <cstdio>
#include <sstream>
namespace openatc {
namespace {
const ImVec4 accent{0.31f,0.79f,0.94f,1},muted{0.61f,0.67f,0.74f,1};
void formText(const char* label,std::string& value,size_t capacity=128){ImGui::TableNextColumn();ImGui::TextDisabled("%s",label);ImGui::SetNextItemWidth(-1);std::string identifier="##"+std::string(label);editText(identifier.c_str(),value,capacity);}
void formInteger(const char* label,int& value,int step=1){ImGui::TableNextColumn();ImGui::TextDisabled("%s",label);ImGui::SetNextItemWidth(-1);std::string identifier="##"+std::string(label);ImGui::InputInt(identifier.c_str(),&value,step);}
void formNumber(const char* label,double& value,double step=100){ImGui::TableNextColumn();ImGui::TextDisabled("%s",label);ImGui::SetNextItemWidth(-1);std::string identifier="##"+std::string(label);ImGui::InputDouble(identifier.c_str(),&value,step,step*10,"%.0f");}
}
void Interface::planPage(const State& state){ImGui::BeginDisabled(importing_||!engine_.connected());if(ImGui::Button(importing_?"Downloading OFP...":"Import from SimBrief")){importing_=true;engine_.post("/simbrief",{{"userid",settings_.simbriefId}});}ImGui::EndDisabled();ImGui::SameLine();ImGui::TextDisabled("Latest generated OFP / Pilot ID: %s",settings_.simbriefId.empty()?"set in Settings":settings_.simbriefId.c_str());if(!planNotice_.empty())ImGui::TextWrapped("%s",planNotice_.c_str());
    if(ImGui::BeginTabBar("DispatchTabs")){
        if(ImGui::BeginTabItem("Flight & route")){sectionTitle("FLIGHT DETAILS");if(ImGui::BeginTable("FlightFields",3,ImGuiTableFlags_SizingStretchSame)){formText("Callsign",draft_.callsign,32);formText("Aircraft ICAO",draft_.aircraft,12);formText("Registration",draft_.registration,32);formText("Departure ICAO",draft_.departure,8);formText("Destination ICAO",draft_.destination,8);formText("Alternate ICAO",draft_.alternate,8);formText("Departure runway",draft_.runway,12);formText("Arrival runway",draft_.arrivalRunway,12);formInteger("Cost index",draft_.costIndex);formInteger("Cruise altitude (ft)",draft_.cruiseFeet,1000);formInteger("Initial altitude (ft)",draft_.initialAltitudeFeet,1000);formNumber("Enroute time (min)",draft_.estimatedMinutes,5);formText("Departure stand",draft_.departureStand);formText("Arrival stand",draft_.arrivalStand);ImGui::EndTable();}sectionTitle("ROUTE");editParagraph("##Route",draft_.route,86);ImGui::TextDisabled("Source: %s   AIRAC: %s   %zu mapped fixes",draft_.source.c_str(),draft_.airac.empty()?"unknown":draft_.airac.c_str(),draft_.fixes.size());ImGui::EndTabItem();}
        if(ImGui::BeginTabItem("Procedures")){sectionTitle("DEPARTURE & ARRIVAL");if(ImGui::BeginTable("ProcedureFields",2,ImGuiTableFlags_SizingStretchSame)){formText("SID",draft_.sid);formText("SID transition",draft_.sidTransition);formText("STAR",draft_.star);formText("STAR transition",draft_.starTransition);formText("Approach",draft_.approach);ImGui::EndTable();}ImGui::BeginDisabled(loadingAirport_);if(ImGui::Button("Load departure procedures"))loadAirport(draft_.departure);ImGui::SameLine();if(ImGui::Button("Load arrival procedures"))loadAirport(draft_.destination);ImGui::EndDisabled();ImGui::TextWrapped("%s",airportNotice_.c_str());ImGui::TextDisabled("Click a procedure from %s to use its name and transition.",airport_.icao.c_str());
            if(ImGui::BeginTable("ProcedureList",3,ImGuiTableFlags_RowBg|ImGuiTableFlags_ScrollY,{0,260})){ImGui::TableSetupColumn("Type");ImGui::TableSetupColumn("Procedure");ImGui::TableSetupColumn("Transition");ImGui::TableHeadersRow();int index=0;for(const auto& procedure:airport_.procedures){ImGui::PushID(index++);ImGui::TableNextRow();ImGui::TableNextColumn();ImGui::TextUnformatted(procedure.type.c_str());ImGui::TableNextColumn();if(ImGui::Selectable(procedure.name.c_str(),false,ImGuiSelectableFlags_SpanAllColumns)){if(procedure.type=="SID"&&airport_.icao==draft_.departure){draft_.sid=procedure.name;draft_.sidTransition=procedure.transition;}else if(procedure.type=="STAR"&&airport_.icao==draft_.destination){draft_.star=procedure.name;draft_.starTransition=procedure.transition;}else if(procedure.type=="APPCH"&&airport_.icao==draft_.destination)draft_.approach=procedure.name;}ImGui::TableNextColumn();ImGui::TextUnformatted(procedure.transition.c_str());ImGui::PopID();}ImGui::EndTable();}ImGui::TextWrapped("Procedure names are read from installed CIFP data. Leg constraints and aircraft performance are not calculated here.");ImGui::EndTabItem();}
        if(ImGui::BeginTabItem("Fuel & payload")){sectionTitle("LOAD SHEET / KILOGRAMS");if(ImGui::BeginTable("LoadFields",3,ImGuiTableFlags_SizingStretchSame)){formInteger("Passengers",draft_.passengers);formNumber("Payload (kg)",draft_.payloadKg);formNumber("Cargo (kg)",draft_.cargoKg);formNumber("Block fuel (kg)",draft_.blockFuelKg);formNumber("Trip fuel (kg)",draft_.tripFuelKg);formNumber("Taxi fuel (kg)",draft_.taxiFuelKg);formNumber("Reserve + contingency (kg)",draft_.reserveFuelKg);formNumber("Alternate fuel (kg)",draft_.alternateFuelKg);formNumber("Zero fuel weight (kg)",draft_.zeroFuelWeightKg);formNumber("Takeoff weight (kg)",draft_.takeoffWeightKg);formNumber("Landing weight (kg)",draft_.landingWeightKg);ImGui::EndTable();}ImGui::TextWrapped("Imported values are normalized to kg. This dispatch sheet does not load fuel or passengers into the aircraft. SimBrief remains the performance and fuel-planning source.");ImGui::EndTabItem();}
        ImGui::EndTabBar();}
    ImGui::Spacing();ImGui::Separator();ImGui::BeginDisabled(!engine_.connected()||(state.phase!=Phase::Parked&&state.phase!=Phase::Finished));if(ImGui::Button("Use flight for ATC",{190,40})){try{validateFlightPlan(draft_);engine_.post("/plan",draft_);}catch(const std::exception& error){planNotice_=error.what();}}ImGui::EndDisabled();if(state.phase!=Phase::Parked&&state.phase!=Phase::Finished){ImGui::SameLine();ImGui::TextDisabled("Active flight: reset in Settings to replace it.");}
}
void Interface::taxiPage(const State& state){ImGui::BeginDisabled(loadingAirport_);if(ImGui::Button("Departure airport"))loadAirport(state.plan.departure);ImGui::SameLine();if(ImGui::Button("Arrival airport"))loadAirport(state.plan.destination);ImGui::EndDisabled();ImGui::SameLine();if(ImGui::Button("Fit map")){zoom_=1;pan_={};}ImGui::TextWrapped("%s",airportNotice_.c_str());
    ImGui::Checkbox("Taxiways",&settings_.showTaxiways);ImGui::SameLine();ImGui::Checkbox("Parking",&settings_.showParking);ImGui::SameLine();ImGui::Checkbox("Approved route",&settings_.showTaxiRoute);ImGui::SameLine();ImGui::Checkbox("Aircraft",&settings_.showOwnship);ImGui::SameLine();ImGui::Checkbox("Labels",&settings_.showLabels);
    ImGui::SetNextItemWidth(260);if(ImGui::BeginCombo("Arrival parking",state.plan.arrivalStand.empty()?"Select a stand":state.plan.arrivalStand.c_str())){for(const auto& parking:airport_.parking)if(ImGui::Selectable(parking.name.c_str(),parking.name==state.plan.arrivalStand)){draft_.arrivalStand=parking.name;engine_.post("/plan/parking",{{"stand",parking.name}});}ImGui::EndCombo();}
    if(state.taxiClearance.approved&&state.taxiClearance.airport==airport_.icao)ImGui::TextWrapped("%s",state.taxiClearance.instructions.c_str());else ImGui::TextDisabled("No approved taxi route for this airport. Request taxi on the ATC page.");airportCanvas(state);
}
void Interface::cruisePage(const State& state){float width=(ImGui::GetContentRegionAvail().x-24)/3;metric("ALTITUDE",std::to_string(static_cast<int>(state.telemetry.altitudeFeet))+" ft",width);ImGui::SameLine();metric("GROUND SPEED",std::to_string(static_cast<int>(state.telemetry.groundSpeedKnots))+" kt",width);ImGui::SameLine();metric("VERTICAL SPEED",std::to_string(static_cast<int>(state.telemetry.verticalSpeedFpm))+" fpm",width);sectionTitle("FLIGHT PROGRESS");ImGui::Text("Stage: %s",phaseName(state.phase).c_str());ImGui::Text("Position %.5f, %.5f   /   Heading %.0f",state.telemetry.latitude,state.telemetry.longitude,state.telemetry.headingDegrees);ImGui::Text("Planned cruise %d ft   /   %s > %s",state.plan.cruiseFeet,state.plan.departure.c_str(),state.plan.destination.c_str());if(state.telemetry.positionValid&&!state.plan.fixes.empty()){const auto& destination=state.plan.fixes.back();double remaining=distanceNm(state.telemetry.latitude,state.telemetry.longitude,destination.latitude,destination.longitude);ImGui::Text("Direct distance to destination: %.0f NM",remaining);if(state.telemetry.groundSpeedKnots>30)ImGui::Text("Time at present groundspeed: %.0f min (direct)",remaining/state.telemetry.groundSpeedKnots*60);}ImGui::TextWrapped("Route: %s",state.plan.route.c_str());if(!state.plan.fixes.empty())weatherCanvas(state,std::max(220.0f,ImGui::GetContentRegionAvail().y-30));}
void Interface::arrivalPage(const State& state){ImGui::TextColored(accent,"%s  /  RWY %s  /  %s  %s",state.plan.destination.c_str(),state.plan.arrivalRunway.c_str(),state.plan.star.c_str(),state.plan.approach.c_str());ImGui::SetNextItemWidth(230);ImGui::SliderFloat("Target (ft MSL)",&targetFeet_,0,15000,"%.0f");ImGui::SameLine();ImGui::SetNextItemWidth(180);ImGui::SliderFloat("Descent angle",&descentAngle_,1,6,"%.1f deg");ImGui::Checkbox("Planned profile",&settings_.showPlannedDescent);ImGui::SameLine();ImGui::Checkbox("Current trajectory",&settings_.showCurrentDescent);
    double altitude=state.telemetry.altitudeFeet,required=descentDistanceNm(altitude,targetFeet_,descentAngle_);float width=(ImGui::GetContentRegionAvail().x-24)/3;metric("DESCENT DISTANCE",std::to_string(static_cast<int>(std::lround(required)))+" NM",width);ImGui::SameLine();metric("CURRENT V/S",std::to_string(static_cast<int>(state.telemetry.verticalSpeedFpm))+" fpm",width);ImGui::SameLine();metric("TARGET",std::to_string(static_cast<int>(targetFeet_))+" ft",width);
    ImVec2 origin=ImGui::GetCursorScreenPos(),size{ImGui::GetContentRegionAvail().x,300};ImGui::InvisibleButton("DescentProfile",size);auto* draw=ImGui::GetWindowDrawList();draw->AddRectFilled(origin,{origin.x+size.x,origin.y+size.y},IM_COL32(21,30,40,255),7);double maximumAltitude=std::max({altitude,static_cast<double>(state.plan.cruiseFeet),static_cast<double>(targetFeet_)+3000.0})*1.1;double maximumDistance=std::max(40.0,required*1.3);auto project=[&](double distance,double height){return ImVec2{origin.x+65+static_cast<float>(distance/maximumDistance)*(size.x-90),origin.y+size.y-42-static_cast<float>(height/maximumAltitude)*(size.y-66)};};
    for(int grid=0;grid<=4;++grid){double height=maximumAltitude*grid/4;auto start=project(0,height),end=project(maximumDistance,height);draw->AddLine(start,end,IM_COL32(49,63,79,255));char label[32];std::snprintf(label,sizeof(label),"%.0f",height);draw->AddText({origin.x+8,start.y-8},IM_COL32(162,179,195,255),label);double distance=maximumDistance*grid/4;auto tick=project(distance,0);std::snprintf(label,sizeof(label),"%.0f NM",distance);draw->AddText({tick.x-20,tick.y+12},IM_COL32(162,179,195,255),label);}
    draw->PushClipRect({origin.x+60,origin.y+10},{origin.x+size.x-12,origin.y+size.y-37},true);
    if(settings_.showPlannedDescent){draw->AddLine(project(0,std::max(altitude,static_cast<double>(targetFeet_))),project(required,targetFeet_),IM_COL32(79,202,240,255),3);draw->AddLine(project(required,targetFeet_),project(maximumDistance,targetFeet_),IM_COL32(79,202,240,255),2);}
    if(settings_.showCurrentDescent&&state.telemetry.groundSpeedKnots>30){double projected=altitude+state.telemetry.verticalSpeedFpm*(maximumDistance/state.telemetry.groundSpeedKnots*60);draw->AddLine(project(0,altitude),project(maximumDistance,projected),IM_COL32(255,191,98,255),3);}draw->AddCircleFilled(project(0,altitude),5,IM_COL32(242,247,250,255));draw->PopClipRect();ImGui::TextColored(accent,"Blue: planned geometric descent");ImGui::SameLine();ImGui::TextColored({1,0.75f,0.39f,1},"Amber: current V/S + groundspeed");ImGui::TextWrapped("Distance runs forward from your present position. The current line uses measured vertical speed; it is unavailable below 30 kt. The planned line excludes procedure constraints and deceleration.");
}
void Interface::airportsPage(const State& state){ImGui::SetNextItemWidth(100);editText("ICAO",airportCode_,8,ImGuiInputTextFlags_CharsUppercase);ImGui::SameLine();ImGui::BeginDisabled(loadingAirport_);if(ImGui::Button(loadingAirport_?"Loading...":"Load airport"))loadAirport(airportCode_);ImGui::EndDisabled();ImGui::TextColored(accent,"%s   %s   /   %.0f ft",airport_.icao.c_str(),airport_.name.c_str(),airport_.elevationFeet);ImGui::TextWrapped("%s",airportNotice_.c_str());
    if(ImGui::BeginTabBar("AirportTabs")){
        if(ImGui::BeginTabItem("Overview")){ImGui::Checkbox("3D orbit",&orbitView_);ImGui::SameLine();ImGui::Checkbox("Demo buildings",&showBuildings_);ImGui::SameLine();ImGui::Checkbox("Runways",&showRunways_);ImGui::SameLine();ImGui::Checkbox("Taxiways",&settings_.showTaxiways);ImGui::SameLine();ImGui::Checkbox("Parking",&settings_.showParking);ImGui::SameLine();ImGui::Checkbox("Navaids",&showNavaids_);ImGui::SameLine();ImGui::Checkbox("Labels",&settings_.showLabels);airportCanvas(state);ImGui::EndTabItem();}
        if(ImGui::BeginTabItem("Frequencies")){if(ImGui::BeginTable("Frequencies",3,ImGuiTableFlags_RowBg|ImGuiTableFlags_BordersInnerH)){ImGui::TableSetupColumn("Service");ImGui::TableSetupColumn("Name");ImGui::TableSetupColumn("MHz");ImGui::TableHeadersRow();for(const auto& frequency:airport_.frequencies){ImGui::TableNextRow();ImGui::TableNextColumn();ImGui::TextUnformatted(frequency.service.c_str());ImGui::TableNextColumn();ImGui::TextUnformatted(frequency.name.c_str());ImGui::TableNextColumn();ImGui::Text("%.3f",frequency.khz/1000.0);}ImGui::EndTable();}if(airport_.frequencies.empty())ImGui::TextWrapped("No communications frequencies in this airport's scenery data.");ImGui::EndTabItem();}
        if(ImGui::BeginTabItem("ILS / navaids")){ImGui::TextWrapped("ILS, localizer and glideslope for this airport; VOR, NDB and DME within 80 NM. NDB frequencies are in kHz; other frequencies are in MHz.");if(ImGui::BeginTable("Navaids",5,ImGuiTableFlags_RowBg|ImGuiTableFlags_ScrollY,{0,std::max(180.0f,ImGui::GetContentRegionAvail().y-35)})){for(const char* title:{"Type","ID","Frequency","Runway","Name / details"})ImGui::TableSetupColumn(title);ImGui::TableHeadersRow();for(const auto& navaid:airport_.navaids){ImGui::TableNextRow();ImGui::TableNextColumn();ImGui::TextUnformatted(navaid.type.c_str());ImGui::TableNextColumn();ImGui::TextUnformatted(navaid.identifier.c_str());ImGui::TableNextColumn();if(navaid.frequency>0)ImGui::Text(navaid.type=="NDB"?"%.0f kHz":"%.2f MHz",navaid.frequency);else ImGui::TextUnformatted("-");ImGui::TableNextColumn();ImGui::TextUnformatted(navaid.runway.c_str());ImGui::TableNextColumn();ImGui::TextWrapped("%s",navaid.name.c_str());if(navaid.type=="LOC"||navaid.type=="ILS LOC"||navaid.type=="GS")ImGui::Text("Course %.1f true",navaid.bearing);if(navaid.glideAngle>0)ImGui::Text("Glide angle %.2f",navaid.glideAngle);}ImGui::EndTable();}ImGui::EndTabItem();}
        if(ImGui::BeginTabItem("Runways & stands")){sectionTitle("RUNWAYS");for(const auto& runway:airport_.runways)ImGui::Text("%s / %s   %.0f x %.0f m",runway.firstName.c_str(),runway.secondName.c_str(),std::hypot(runway.second.east-runway.first.east,runway.second.north-runway.first.north),runway.width);sectionTitle("PARKING LOCATIONS");if(ImGui::BeginTable("Stands",4,ImGuiTableFlags_RowBg|ImGuiTableFlags_ScrollY,{0,300})){for(const char* title:{"Stand","Type","Size","Equipment"})ImGui::TableSetupColumn(title);ImGui::TableHeadersRow();for(const auto& parking:airport_.parking){ImGui::TableNextRow();ImGui::TableNextColumn();ImGui::TextUnformatted(parking.name.c_str());ImGui::TableNextColumn();ImGui::TextUnformatted(parking.type.c_str());ImGui::TableNextColumn();ImGui::TextUnformatted(parking.size.c_str());ImGui::TableNextColumn();ImGui::TextUnformatted(parking.equipment.c_str());}ImGui::EndTable();}ImGui::EndTabItem();}
        if(ImGui::BeginTabItem("Procedures")){if(ImGui::BeginTable("AirportProcedures",3,ImGuiTableFlags_RowBg|ImGuiTableFlags_ScrollY,{0,400})){for(const char* title:{"Type","Name","Transition"})ImGui::TableSetupColumn(title);ImGui::TableHeadersRow();for(const auto& procedure:airport_.procedures){ImGui::TableNextRow();ImGui::TableNextColumn();ImGui::TextUnformatted(procedure.type.c_str());ImGui::TableNextColumn();ImGui::TextUnformatted(procedure.name.c_str());ImGui::TableNextColumn();ImGui::TextUnformatted(procedure.transition.c_str());}ImGui::EndTable();}ImGui::EndTabItem();}ImGui::EndTabBar();}
}
void Interface::weatherPage(const State& state){if(weatherStations_.empty())weatherStations_=state.plan.departure+","+state.plan.destination+(state.plan.alternate.empty()?"":","+state.plan.alternate);ImGui::SetNextItemWidth(std::max(200.0f,ImGui::GetContentRegionAvail().x-190));editText("##stations",weatherStations_,256,ImGuiInputTextFlags_CharsUppercase);ImGui::SameLine();ImGui::BeginDisabled(loadingWeather_||!engine_.connected()||(lastWeatherFetch_>0&&uiTimeSeconds()-lastWeatherFetch_<60));if(ImGui::Button(loadingWeather_?"Downloading...":"Refresh weather")){loadingWeather_=true;engine_.post("/weather",{{"stations",weatherStations_}});}ImGui::EndDisabled();ImGui::TextDisabled("Station ICAOs, separated by commas. Add stations along your route.");ImGui::TextWrapped("%s",weatherNotice_.empty()?"Load current METARs to see georeferenced station weather along your flight.":weatherNotice_.c_str());ImGui::Checkbox("Route",&settings_.weatherRoute);ImGui::SameLine();ImGui::Checkbox("Aircraft",&settings_.weatherOwnship);ImGui::SameLine();ImGui::Checkbox("Stations",&settings_.weatherStations);ImGui::SameLine();ImGui::Checkbox("Wind",&settings_.weatherWind);ImGui::SameLine();ImGui::Checkbox("Cloud cover",&settings_.weatherClouds);ImGui::SameLine();ImGui::Checkbox("Labels",&settings_.weatherLabels);if(ImGui::Button("Fit weather map")){weatherZoom_=1;weatherPan_={};}ImGui::SameLine();ImGui::TextDisabled("VFR green / MVFR blue / IFR red / LIFR purple / Unknown grey");weatherCanvas(state,std::max(260.0f,ImGui::GetContentRegionAvail().y-115));ImGui::TextWrapped("Surface station observations from NOAA Aviation Weather Center. This map is not precipitation radar or an airborne weather radar. Hover a station for its report and observation time.");if(lastWeatherFetch_>0)ImGui::TextDisabled("Fetched %.0f minutes ago. Wheel to zoom; drag to pan.",(uiTimeSeconds()-lastWeatherFetch_)/60);}
}
